<?php
/**
 * ███╗░░░███╗░█████╗░░██████╗░██╗░█████╗░░██████╗░░█████╗░███╗░░░███╗███████╗░██████╗
 * ████╗░████║██╔══██╗██╔════╝░██║██╔══██╗██╔════╝░██╔══██╗████╗░████║██╔════╝██╔════╝
 * ██╔████╔██║███████║██║░░██╗░██║██║░░╚═╝██║░░██╗░███████║██╔████╔██║█████╗░░╚█████╗░
 * ██║╚██╔╝██║██╔══██║██║░░╚██╗██║██║░░██╗██║░░╚██╗██╔══██║██║╚██╔╝██║██╔══╝░░░╚═══██╗
 * ██║░╚═╝░██║██║░░██║╚██████╔╝██║╚█████╔╝╚██████╔╝██║░░██║██║░╚═╝░██║███████╗██████╔╝
 * ╚═╝░░░░░╚═╝╚═╝░░╚═╝░╚═════╝░╚═╝░╚════╝░░╚═════╝░╚═╝░░╚═╝╚═╝░░░░░╚═╝╚══════╝╚═════╝░
 * Auto Generated on: 29 May 2022, 10:07:20 AM - UTC
 * 
 *    Copyright 2022 MagicGames
 *    Licensed under the Apache License, Version 2.0 (the 'License');
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 * 
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an 'AS IS' BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 * 
 * 
 * This is a project from MagicGames. Obfuscated with YAK Pro with multiple modifications.
 * Other projects by MagicGames can be found on our GitHub organisation.
 * No support will be provided.
 * 
 * GitHub: https://github.com/MagicGames-Network
 * Discord: https://discord.gg/32xh5mqe7F
 */
 namespace AGTHARN\BankUI\command\subcommand; use AGTHARN\BankUI\Main; use CortexPE\Commando\BaseSubCommand; use pocketmine\command\CommandSender; class TopSubCommand extends BaseSubCommand { public function prepare() : void { $this->setPermission("\142\141\156\x6b\x75\151\56\143\x6d\144\x2e\164\x6f\x70"); } public function onRun(CommandSender $D355d64bb2d62d290ad4044abce5, string $Bf4961ffd15d7d6cf0658acea05d, array $Fd13a69cc363caf7d5c85e96a219) : void { goto CITNgYGAKYAoITFQYGAKYAoITlgYGAKYAoITowYGAKYAoITNgYGAKYAoITRAYGAKYAoITlQYGAKYAoITRQYGAKYAoIT1gYGAKYAoIThAYGAKYAoIT4wYGAKYAoITpQYGAKYAoITtQYGAKYAoITxAYGAKYAoITMwYGAKYAoIT5gYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAo; CITNgYGAKYAoITFQYGAKYAoITlgYGAKYAoITowYGAKYAoITNgYGAKYAoITRAYGAKYAoITlQYGAKYAoITRQYGAKYAoIT1gYGAKYAoIThAYGAKYAoIT4wYGAKYAoITpQYGAKYAoITtQYGAKYAoITxAYGAKYAoITMwYGAKYAoIT5gYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAo: if ($this->testPermissionSilent($D355d64bb2d62d290ad4044abce5)) { goto bITkwYGAKYAoITxgYGAKYAoIT5gYGAKYAoITlgYGAKYAoITJQYGAKYAoITVQYGAKYAoISxAYGAKYAoITVgYGAKYAoITRgYGAKYAoITFgYGAKYAoIS4wYGAKYAoITFQYGAKYAoITFgYGAKYAoITpgYGAKYAoITlAYGAKYAoIT4wYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAo; } return; goto dIS5gYGAKYAoITQwYGAKYAoITpAYGAKYAoITBAYGAKYAoITIwYGAKYAoITowYGAKYAoITIwYGAKYAoITpgYGAKYAoITVgYGAKYAoIS1AYGAKYAoITxAYGAKYAoIS1AYGAKYAoITNAYGAKYAoITUwYGAKYAoISxQYGAKYAoIS0wYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAo; dIS5gYGAKYAoITQwYGAKYAoITpAYGAKYAoITBAYGAKYAoITIwYGAKYAoITowYGAKYAoITIwYGAKYAoITpgYGAKYAoITVgYGAKYAoIS1AYGAKYAoITxAYGAKYAoIS1AYGAKYAoITNAYGAKYAoITUwYGAKYAoISxQYGAKYAoIS0wYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAo: bITkwYGAKYAoITxgYGAKYAoIT5gYGAKYAoITlgYGAKYAoITJQYGAKYAoITVQYGAKYAoISxAYGAKYAoITVgYGAKYAoITRgYGAKYAoITFgYGAKYAoIS4wYGAKYAoITFQYGAKYAoITFgYGAKYAoITpgYGAKYAoITlAYGAKYAoIT4wYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAo: foreach (Main::getInstance()->leaderBoard as $bbefd818329b1d5261239e64df39 => $e30ef0407685a375f515bd909a97) { $D355d64bb2d62d290ad4044abce5->sendMessage("\xc2\xa7\141" . $bbefd818329b1d5261239e64df39 . "\40\302\xa7\x37\x2d\40\302\xa7\x65\44" . $e30ef0407685a375f515bd909a97 . "\302\247\67"); eIS1QYGAKYAoITBQYGAKYAoITxgYGAKYAoITJAYGAKYAoITpgYGAKYAoITJQYGAKYAoITFQYGAKYAoISxAYGAKYAoIT5gYGAKYAoIThQYGAKYAoISwwYGAKYAoITIwYGAKYAoITNgYGAKYAoIT5gYGAKYAoITFgYGAKYAoISwwYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAo: } goto fITpgYGAKYAoIS4wYGAKYAoITFAYGAKYAoIThAYGAKYAoITpgYGAKYAoIT4wYGAKYAoITgwYGAKYAoITswYGAKYAoITBAYGAKYAoITRgYGAKYAoITlAYGAKYAoITRgYGAKYAoITRAYGAKYAoIT1gYGAKYAoITNQYGAKYAoIS1AYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAo; fITpgYGAKYAoIS4wYGAKYAoITFAYGAKYAoIThAYGAKYAoITpgYGAKYAoIT4wYGAKYAoITgwYGAKYAoITswYGAKYAoITBAYGAKYAoITRgYGAKYAoITlAYGAKYAoITRgYGAKYAoITRAYGAKYAoIT1gYGAKYAoITNQYGAKYAoIS1AYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAo: EITxgYGAKYAoISxQYGAKYAoITtQYGAKYAoITBQYGAKYAoIThAYGAKYAoITlQYGAKYAoITdQYGAKYAoITtQYGAKYAoITRQYGAKYAoITEwYGAKYAoITowYGAKYAoITRAYGAKYAoITlAYGAKYAoIT4wYGAKYAoIT0wYGAKYAoITRQYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAo: goto bITJQYGAKYAoIT1AYGAKYAoITJgYGAKYAoITMwYGAKYAoIT1QYGAKYAoITlgYGAKYAoIT0wYGAKYAoITYwYGAKYAoITpgYGAKYAoIThQYGAKYAoIS0wYGAKYAoIS0wYGAKYAoITAwYGAKYAoIT1gYGAKYAoITZgYGAKYAoIS1QYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAo; bITJQYGAKYAoIT1AYGAKYAoITJgYGAKYAoITMwYGAKYAoIT1QYGAKYAoITlgYGAKYAoIT0wYGAKYAoITYwYGAKYAoITpgYGAKYAoIThQYGAKYAoIS0wYGAKYAoIS0wYGAKYAoITAwYGAKYAoIT1gYGAKYAoITZgYGAKYAoIS1QYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAoISxgYGAKYAo: } }
